"""SMTP email sending for the agent.

Two emails per incident:
  1. an immediate "alert received" notification, and
  2. the final root-cause analysis once the LLM responds.
If SMTP is not configured, emails are skipped (and logged) so the agent still
works end-to-end for local testing.
"""

import html
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .config import settings
from .models import Alert

logger = logging.getLogger("agent.mailer")


def _send(subject: str, html_body: str, text_body: str) -> None:
    if not settings.smtp_host:
        logger.warning("SMTP not configured (SMTP_HOST empty); skipping email: %s", subject)
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.mail_from
    msg["To"] = settings.mail_to
    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port, timeout=30) as server:
            if settings.smtp_use_tls:
                server.starttls()
            if settings.smtp_user:
                server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)
        logger.info("email sent: %s", subject)
    except Exception as exc:  # noqa: BLE001
        logger.error("failed to send email '%s': %s", subject, exc)


def send_alert_received(alert: Alert) -> None:
    name = alert.labels.get("alertname", "unknown")
    ns = alert.labels.get("namespace", "n/a")
    pod = alert.labels.get("pod", "n/a")
    severity = alert.labels.get("severity", "n/a")
    summary = alert.annotations.get("summary", "")

    subject = f"[ALERT] {name} ({severity}) - investigating"
    text_body = (
        f"Alert received and under investigation.\n\n"
        f"Alert: {name}\nSeverity: {severity}\nNamespace: {ns}\nPod: {pod}\n"
        f"Summary: {summary}\n\nA root-cause analysis will follow shortly."
    )
    html_body = f"""
    <h2>Alert received - investigating</h2>
    <table cellpadding="6" style="border-collapse:collapse">
      <tr><td><b>Alert</b></td><td>{html.escape(name)}</td></tr>
      <tr><td><b>Severity</b></td><td>{html.escape(severity)}</td></tr>
      <tr><td><b>Namespace</b></td><td>{html.escape(ns)}</td></tr>
      <tr><td><b>Pod</b></td><td>{html.escape(pod)}</td></tr>
      <tr><td><b>Summary</b></td><td>{html.escape(summary)}</td></tr>
    </table>
    <p>A root-cause analysis will follow shortly.</p>
    """
    _send(subject, html_body, text_body)


def send_analysis(alert: Alert, analysis: str) -> None:
    name = alert.labels.get("alertname", "unknown")
    severity = alert.labels.get("severity", "n/a")
    subject = f"[RCA] {name} ({severity}) - root-cause analysis"

    text_body = f"Root-cause analysis for {name}:\n\n{analysis}"
    html_body = f"""
    <h2>Root-cause analysis: {html.escape(name)}</h2>
    <pre style="font-family:Consolas,monospace;white-space:pre-wrap;
                background:#f6f8fa;padding:12px;border-radius:6px">{html.escape(analysis)}</pre>
    <p style="color:#666">Generated by the AI incident-analysis agent. Suggested
    remediations are for human review and were not executed.</p>
    """
    _send(subject, html_body, text_body)
